/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const TUNISIAN_DELEGATIONS: string[] = [
  // Tunis
  'Bab Bhar',
  'Bab Souika',
  'Carthage',
  'Cité El Khadra',
  'Djebel Jelloud',
  'El Kabaria',
  'El Menzah',
  'El Omrane',
  'El Omrane Supérieur',
  'El Ouardia',
  'Ettahrir',
  'Ezzouhour',
  'Hraïria',
  'La Goulette',
  'La Marsa',
  'Le Bardo',
  'Le Kram',
  'Medina',
  'Séjoumi',
  'Sidi El Béchir',
  'Sidi Hassine',
  // Ariana
  'Ariana Ville',
  'Ettadhamen',
  'Kalâat el-Andalous',
  'La Soukra',
  'Mnihla',
  'Raoued',
  'Sidi Thabet',
  // Ben Arous
  'Ben Arous',
  'Bou Mhel el-Bassatine',
  'El Mourouj',
  'Ezzahra',
  'Fouchana',
  'Hammam Chott',
  'Hammam Lif',
  'Mégrine',
  'Mohamedia',
  'Mornag',
  'Nouvelle Médina',
  'Radès',
  // Manouba
  'Borj El Amri',
  'Douar Hicher',
  'El Battan',
  'Jedaida',
  'Manouba',
  'Mornaguia',
  'Oued Ellil',
  'Tebourba',
  // Bizerte
  'Bizerte Nord',
  'Bizerte Sud',
  'Djoumine',
  'El Alia',
  'Ghar El Melh',
  'Ghezala',
  'Mateur',
  'Menzel Bourguiba',
  'Menzel Jemil',
  'Ras Jebel',
  'Sejenane',
  'Tinja',
  'Utique',
  'Zarzouna',
  // Nabeul
  'Béni Khalled',
  'Béni Khiar',
  'Bou Argoub',
  'Dar Chaabane El Fehri',
  'El Haouaria',
  'El Mida',
  'Grombalia',
  'Hammam Ghezèze',
  'Hammamet',
  'Kélibia',
  'Korba',
  'Menzel Bouzelfa',
  'Menzel Temime',
  'Nabeul',
  'Soliman',
  'Takelsa',
  // Zaghouan
  'Bir Mcherga',
  'El Fahs',
  'Ennadhour',
  'Saouaf',
  'Zaghouan',
  'Zriba',
  // Béja
  'Amdoun',
  'Béja Nord',
  'Béja Sud',
  'Goubellat',
  'Medjez el-Bab',
  'Nefza',
  'Téboursouk',
  'Testour',
  'Thibar',
  // Jendouba
  'Aïn Draham',
  'Balta-Bou Aouane',
  'Bou Salem',
  'Fernana',
  'Ghardimaou',
  'Jendouba',
  'Jendouba Nord',
  'Oued Meliz',
  'Tabarka',
  // Le Kef
  'Dahmani',
  'Jérissa',
  'Kalâat Senan',
  'Kalaat Khasba',
  'Ksour',
  'Le Kef Est',
  'Le Kef Ouest',
  'Le Sers',
  'Nebeur',
  'Sakiet Sidi Youssef',
  'Tajerouine',
  'Touiref',
  // Siliana
  'Bargou',
  'Bou Arada',
  'El Aroussa',
  'El Krib',
  'Gaâfour',
  'Kesra',
  'Makthar',
  'Rouhia',
  'Sidi Bou Rouis',
  'Siliana Nord',
  'Siliana Sud',
  // Kairouan
  'Bou Hajla',
  'Chebika',
  'Cherarda',
  'El Alâa',
  'Haffouz',
  'Hajeb El Ayoun',
  'Kairouan Nord',
  'Kairouan Sud',
  'Nasrallah',
  'Oueslatia',
  'Sbikha',
  // Kasserine
  'El Ayoun',
  'Ezzouhour',
  'Fériana',
  'Foussana',
  'Haïdra',
  'Hassi El Ferid',
  'Jedelienne',
  'Kasserine Nord',
  'Kasserine Sud',
  'Majel Bel Abbès',
  'Sbeïtla',
  'Sbiba',
  'Thala',
  // Sidi Bouzid
  'Bir El Hafey',
  'Cebbala Ouled Asker',
  'Jilma',
  'Menzel Bouzaiane',
  'Meknassy',
  'Mezzouna',
  'Ouled Haffouz',
  'Regueb',
  'Sidi Ali Ben Aoun',
  'Sidi Bouzid Est',
  'Sidi Bouzid Ouest',
  'Souk Jedid',
  // Sousse
  'Akouda',
  'Bouficha',
  'Enfida',
  'Hammam Sousse',
  'Hergla',
  'Kalâa Kebira',
  'Kalâa Seghira',
  'Kondar',
  'Msaken',
  'Sidi Bou Ali',
  'Sidi El Hani',
  'Sousse Jawhara',
  'Sousse Médina',
  'Sousse Riadh',
  'Sousse Sidi Abdelhamid',
  // Monastir
  'Bekalta',
  'Bembla',
  'Beni Hassen',
  'Jemmal',
  'Ksar Hellal',
  'Ksibet el-Médiouni',
  'Moknine',
  'Monastir',
  'Ouerdanine',
  'Sahline',
  'Sayada-Lamta-Bou Hajar',
  'Téboulba',
  'Zeramdine',
  // Mahdia
  'Bou Merdes',
  'Chebba',
  'Chorbane',
  'El Djem',
  'Essouassi',
  'Hbira',
  'Ksour Essef',
  'Mahdia',
  'Melloulèche',
  'Ouled Chamekh',
  'Sidi Alouane',
  // Sfax
  'Agareb',
  'Bir Ali Ben Khalifa',
  'El Amra',
  'El Hencha',
  'Esskhira',
  'Graïba',
  'Jebeniana',
  'Kerkennah',
  'Mahrès',
  'Menzel Chaker',
  'Sakiet Eddaïer',
  'Sakiet Ezzit',
  'Sfax Ouest',
  'Sfax Sud',
  'Sfax Ville',
  'Thyna',
  // Gabès
  'El Hamma',
  'El Métouia',
  'Gabès Médina',
  'Gabès Ouest',
  'Gabès Sud',
  'Ghannouch',
  'Mareth',
  'Matmata',
  'Menzel El Habib',
  'Nouvelle Matmata',
  // Médenine
  'Ajim',
  'Ben Gardane',
  'Beni Khedache',
  'Houmt Souk',
  'Médenine Nord',
  'Médenine Sud',
  'Midoun',
  'Sidi Makhlouf',
  'Zarzis',
  // Tataouine
  'Bir Lahmar',
  'Dhehiba',
  'Ghomrassen',
  'Remada',
  'Smâr',
  'Tataouine Nord',
  'Tataouine Sud',
  // Gafsa
  'Belkhir',
  'El Guettar',
  'El Ksar',
  'Gafsa Nord',
  'Gafsa Sud',
  'Mdhilla',
  'Métlaoui',
  'Moularès',
  'Redeyef',
  'Sened',
  'Sidi Aïch',
  // Tozeur
  'Degache',
  'Hammet Jérid',
  'Nefta',
  'Tameghza',
  'Tozeur',
  // Kébili
  'Douz Nord',
  'Douz Sud',
  'Faouar',
  'Kébili Nord',
  'Kébili Sud',
  'Souk Lahad',
];
