-- =============================================================
-- AAJ Website — MySQL/MariaDB schema (cPanel)
-- Charset: utf8mb4 — Collation: utf8mb4_unicode_ci
-- Timestamps are stored in UTC and returned as ISO-8601 strings.
-- IDs are VARCHAR(64) — preserves existing Firestore document IDs
-- when a migration is performed, and allows random string IDs
-- generated by the API for new documents.
-- =============================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- -------------------------------------------------------------
-- roles
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id            VARCHAR(64)  NOT NULL,
  name          VARCHAR(100) NOT NULL,
  description   TEXT NULL,
  permissions   JSON NOT NULL,
  is_system     TINYINT(1) NOT NULL DEFAULT 0,
  is_all_access TINYINT(1) NOT NULL DEFAULT 0,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_roles_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- users (uid is the primary key — preserved from Firebase Auth
-- when migrating; newly created accounts get a generated uid)
-- Passwords are hashed with password_hash() (bcrypt/argon2id).
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  uid                 VARCHAR(64)  NOT NULL,
  email               VARCHAR(255) NOT NULL,
  password_hash       VARCHAR(255) NULL,
  must_reset          TINYINT(1)   NOT NULL DEFAULT 0,
  display_name        VARCHAR(200) NOT NULL DEFAULT '',
  first_name          VARCHAR(100) NULL,
  last_name           VARCHAR(100) NULL,
  role                VARCHAR(64)  NOT NULL DEFAULT 'member',
  status              VARCHAR(32)  NOT NULL DEFAULT 'pending',
  category            VARCHAR(100) NULL,
  member_type         VARCHAR(100) NULL,
  member_type_letter  CHAR(1)      NULL,
  birth_date          VARCHAR(10)  NULL,
  license_number      VARCHAR(100) NULL,
  mobile              VARCHAR(50)  NULL,
  address             VARCHAR(200) NULL,
  photo_url           TEXT NULL,
  cotisations         JSON NULL,
  created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at         DATETIME NULL,
  PRIMARY KEY (uid),
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_role (role),
  KEY idx_users_status (status),
  KEY idx_users_display_name (display_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- news
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS news (
  id         VARCHAR(64) NOT NULL,
  title      VARCHAR(300) NOT NULL,
  content    TEXT NOT NULL,
  date       VARCHAR(32) NULL,
  type       VARCHAR(32) NULL,
  category   VARCHAR(100) NULL,
  image_url  TEXT NULL,
  file_url   TEXT NULL,
  file_name  VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_news_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- partners
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS partners (
  id         VARCHAR(64) NOT NULL,
  name       VARCHAR(200) NOT NULL,
  logo_url   TEXT NULL,
  category   VARCHAR(32) NULL,
  level      VARCHAR(32) NULL,
  joined     VARCHAR(32) NULL,
  is_visible TINYINT(1) NOT NULL DEFAULT 1,
  website    VARCHAR(300) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_partners_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- commission_pvs
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS commission_pvs (
  id         VARCHAR(64) NOT NULL,
  town       VARCHAR(100) NOT NULL,
  date       VARCHAR(32) NULL,
  `count`    INT NOT NULL DEFAULT 0,
  file_url   TEXT NULL,
  file_name  VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pvs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- contact_messages
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
  id         VARCHAR(64) NOT NULL,
  user_id    VARCHAR(64) NOT NULL,
  user_email VARCHAR(255) NULL,
  subject    VARCHAR(300) NOT NULL,
  message    TEXT NOT NULL,
  file_url   TEXT NULL,
  file_name  VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_msgs_user (user_id),
  KEY idx_msgs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- documents (library)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS documents (
  id           VARCHAR(64) NOT NULL,
  name         VARCHAR(300) NOT NULL,
  url          TEXT NULL,
  category     VARCHAR(100) NOT NULL DEFAULT '',
  sub_category VARCHAR(100) NULL,
  file_type    VARCHAR(50) NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_docs_category (category),
  KEY idx_docs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- profile_updates
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profile_updates (
  id             VARCHAR(64) NOT NULL,
  uid            VARCHAR(64) NOT NULL,
  user_email     VARCHAR(255) NOT NULL,
  first_name     VARCHAR(100) NULL,
  last_name      VARCHAR(100) NULL,
  mobile         VARCHAR(50)  NULL,
  category       VARCHAR(64)  NULL,
  license_number VARCHAR(100) NULL,
  address        VARCHAR(200) NULL,
  status         VARCHAR(32)  NOT NULL DEFAULT 'pending',
  created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_profile_updates_uid (uid),
  KEY idx_profile_updates_status (status),
  KEY idx_profile_updates_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- event_registrations
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_registrations (
  id          VARCHAR(64) NOT NULL,
  full_name   VARCHAR(200) NOT NULL,
  email       VARCHAR(255) NOT NULL,
  event_title VARCHAR(300) NOT NULL,
  message     TEXT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_events_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- membership_applications
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS membership_applications (
  id                 VARCHAR(64) NOT NULL,
  full_name          VARCHAR(200) NOT NULL,
  first_name         VARCHAR(100) NULL,
  last_name          VARCHAR(100) NULL,
  email              VARCHAR(255) NOT NULL,
  phone              VARCHAR(50)  NOT NULL,
  category           VARCHAR(64)  NOT NULL,
  matricule          VARCHAR(100) NULL,
  city               VARCHAR(100) NOT NULL,
  birth_date         VARCHAR(10)  NULL,
  member_type_letter CHAR(1)      NULL,
  cv_file_name       VARCHAR(255) NULL,
  status             VARCHAR(32)  NOT NULL DEFAULT 'pending',
  created_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_memberships_status (status),
  KEY idx_memberships_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- partner_applications
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS partner_applications (
  id               VARCHAR(64) NOT NULL,
  contact_name     VARCHAR(200) NOT NULL,
  email            VARCHAR(255) NOT NULL,
  phone            VARCHAR(50)  NOT NULL,
  company_name     VARCHAR(300) NOT NULL,
  activity         VARCHAR(200) NOT NULL,
  sponsorship_type VARCHAR(32)  NOT NULL,
  message          TEXT NULL,
  status           VARCHAR(32)  NOT NULL DEFAULT 'pending',
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_partnerapps_status (status),
  KEY idx_partnerapps_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- password_resets — short-lived tokens sent by email
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS password_resets (
  token      VARCHAR(128) NOT NULL,
  uid        VARCHAR(64)  NOT NULL,
  email      VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  used_at    DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (token),
  KEY idx_resets_uid (uid),
  KEY idx_resets_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- config — admin-editable key/value lookup lists (villes, memberTypes)
-- Each row is a single named document; `value` is a JSON blob the
-- frontend spreads onto the snapshot (e.g. value.list is the array).
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS config (
  id         VARCHAR(64) NOT NULL,
  value      JSON NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Post-migration hardening (safe to re-run; IF NOT EXISTS avoids error
-- when the column is already present). Covers instances that were
-- provisioned before member-type + birth-date tracking landed.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS member_type        VARCHAR(100) NULL AFTER category,
  ADD COLUMN IF NOT EXISTS member_type_letter CHAR(1)      NULL AFTER member_type,
  ADD COLUMN IF NOT EXISTS birth_date         VARCHAR(10)  NULL AFTER member_type_letter;

-- -------------------------------------------------------------
-- chat_channels — internal messaging channels (general + custom)
-- member_uids/last_message stored as JSON for simplicity
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_channels (
  id                VARCHAR(64)  NOT NULL,
  name              VARCHAR(200) NOT NULL,
  description       TEXT NULL,
  type              VARCHAR(32)  NOT NULL DEFAULT 'custom',
  status            VARCHAR(32)  NOT NULL DEFAULT 'pending',
  is_all_members    TINYINT(1)   NOT NULL DEFAULT 0,
  member_uids       JSON NULL,
  created_by        VARCHAR(64)  NOT NULL,
  created_by_name   VARCHAR(200) NOT NULL DEFAULT '',
  approved_by       VARCHAR(64)  NULL,
  approved_at       DATETIME NULL,
  rejected_reason   TEXT NULL,
  icon_color        VARCHAR(16)  NULL,
  last_message      JSON NULL,
  last_activity_at  DATETIME NULL,
  created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chat_channels_status (status),
  KEY idx_chat_channels_activity (last_activity_at),
  KEY idx_chat_channels_creator (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- chat_messages — one row per message (subcollection-flattened
-- with channel_id column)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
  id               VARCHAR(64)  NOT NULL,
  channel_id       VARCHAR(64)  NOT NULL,
  text             TEXT NULL,
  sender_id        VARCHAR(64)  NOT NULL,
  sender_name      VARCHAR(200) NOT NULL DEFAULT '',
  sender_photo     TEXT NULL,
  reply_to         JSON NULL,
  attachment_url   TEXT NULL,
  attachment_id    VARCHAR(64)  NULL,
  attachment_name  VARCHAR(255) NULL,
  attachment_type  VARCHAR(120) NULL,
  attachment_size  BIGINT NULL,
  reactions        JSON NULL,
  edited_at        DATETIME NULL,
  deleted_at       DATETIME NULL,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chat_msgs_channel (channel_id, created_at),
  KEY idx_chat_msgs_sender (sender_id),
  CONSTRAINT fk_chat_msgs_channel
    FOREIGN KEY (channel_id) REFERENCES chat_channels(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- chat_channel_reads — per-user read marker per channel
-- id is the composite "{channel_id}_{uid}" so the existing
-- single-key collection router can address rows directly.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_channel_reads (
  id            VARCHAR(160) NOT NULL,
  channel_id    VARCHAR(64)  NOT NULL,
  uid           VARCHAR(64)  NOT NULL,
  last_read_at  DATETIME NOT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chat_reads_uid (uid),
  KEY idx_chat_reads_channel (channel_id),
  CONSTRAINT fk_chat_reads_channel
    FOREIGN KEY (channel_id) REFERENCES chat_channels(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------
-- files — metadata for uploaded files stored on disk
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS files (
  id           VARCHAR(64) NOT NULL,
  folder       VARCHAR(100) NOT NULL,
  owner_uid    VARCHAR(64) NULL,
  original_name VARCHAR(255) NOT NULL,
  stored_path  VARCHAR(500) NOT NULL,
  mime_type    VARCHAR(120) NOT NULL,
  size_bytes   BIGINT NOT NULL DEFAULT 0,
  access       VARCHAR(32) NOT NULL DEFAULT 'private',
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_files_folder (folder),
  KEY idx_files_owner (owner_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- Upgrades from older databases
-- =============================================================
-- Deux options pour les bases déjà déployées avant l'ajout d'un
-- nouveau champ :
--
-- 1. Scripts PHP CLI idempotents dans api/scripts/ (pre-emptif) :
--      php scripts/migrate-archived-at.php    (ajoute users.archived_at)
--
-- 2. Auto-migration (self-healing) intégrée au backend : la fonction
--    ensure_column() dans lib/db.php crée les colonnes whitelistées
--    automatiquement au premier besoin. Actuellement couvre :
--      users.archived_at  — crée lors du premier archivage.
--
-- Les deux approches sont idempotentes — safe à relancer.
